In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt

In [2]:
# How likely is it that you roll doubles when rolling two dice?

n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[1, 5],
       [6, 3],
       [2, 4],
       ...,
       [1, 2],
       [1, 3],
       [4, 2]])

In [28]:
rolls[:,0] == rolls[:,1]

doubles = (rolls[:,0] == rolls[:,1]).astype(int).mean()
doubles

# answer: 16.2%

0.1624

In [95]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

n_trials = nrows = 10_000
n_coin = ncols = 8

flips = np.random.choice([0, 1], n_trials * n_coin).reshape(nrows, ncols)
flips

array([[1, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1]])

In [98]:
flips = pd.DataFrame(flips)
three_heads = (flips.sum(axis=1) == 3).mean()
three_heads

0.2164

In [99]:
more_than_three_heads = (flips.sum(axis=1) > 3).mean()
more_than_three_heads

0.6365

In [104]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

n_trials = nrows = 10**5
n_bills = ncols = 2

alum = np.random.choice([0, 0, 0, 1], n_trials * n_dice).reshape(nrows, ncols)
alum

# alum = np.random.choice([0, 1], n_trials * n_dice, p= (.75 , .25).reshape(nrows, ncols)

array([[1, 0],
       [0, 0],
       [1, 1],
       ...,
       [1, 0],
       [0, 1],
       [0, 1]])

In [106]:
DS_student = (alum.sum(axis=1) == 2).mean()
DS_student

0.06255

In [128]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the 
# snack vending machine. If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)

n_trials = nrows = 10**5
n_days = ncols = 5

poptarts = np.random.normal(3, 1.5, n_trials * n_days).reshape(nrows, ncols)
poptarts

array([[ 1.32584843,  2.17609697,  2.426834  ,  3.14399814,  4.12117734],
       [ 2.85382265,  0.09088141,  4.85193434,  3.80415846,  2.266643  ],
       [ 6.64204044,  3.90751457,  4.04025643,  3.89820645,  4.02076782],
       ...,
       [ 1.57924731,  2.61686198,  4.29127373,  2.06977689,  3.3377    ],
       [ 5.32684394,  6.86504489,  1.93571865,  4.76866728,  3.04523395],
       [ 0.97244044,  1.89127534, -0.75495083,  4.79680119,  4.70998968]])

In [130]:
poptarts.round()

array([[ 1.,  2.,  2.,  3.,  4.],
       [ 3.,  0.,  5.,  4.,  2.],
       [ 7.,  4.,  4.,  4.,  4.],
       ...,
       [ 2.,  3.,  4.,  2.,  3.],
       [ 5.,  7.,  2.,  5.,  3.],
       [ 1.,  2., -1.,  5.,  5.]])

In [133]:
yes_friday = (poptarts.sum(axis=1) < 17).mean()
yes_friday

0.72422

In [138]:
# Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


men_height = np.random.normal(178, 8, 10**5)
women_height = np.random.normal(170, 6, 10**5)
woman_taller = (women_height > men_height).mean()
woman_taller

0.21254

In [184]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, 

chance = 1/250
fifty = (np.random.random((10**5, 50)) > chance).prod(axis=1).mean()
fifty

0.81979

In [186]:
# no one has an installation issue? 100 students?

one_hundred = (np.random.random((10**5, 100)) > chance).prod(axis=1).mean()
one_hundred

0.66724

In [187]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

one_fifty = (np.random.random((10**5, 150)) > chance).prod(axis=1).mean()
one_fifty

0.54639

In [188]:
# How likely is it that 450 students all download anaconda without an issue?

all = (np.random.random((10**5, 450)) > chance).prod(axis=1).mean()
all

0.16514

In [197]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

n_trials = nrows = 10**5
n_days = ncols = 3

trucks = np.random.choice([0,1], size=(nrows, ncols), p=[.7, .3])
trucks.sum(axis=1).mean()

#.99

0.89884

In [205]:
# How likely is it that a food truck will show up sometime this week?

n_trials = nrows = 10**5
n_days = ncols = 5


0.0003

In [208]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

birthday_23 = pd.DataFrame(np.random.randint(0,365,(10_000,23)))
share_23 = birthday_23.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_23

0.509

In [207]:
birthday_20 = pd.DataFrame(np.random.randint(0,365,(10_000,20)))
share_20 = birthday_20.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_20

0.4084